api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("users/<int:telegram_id>/", views.telegram_user_view),
    path("users/", views.telegram_user_view),
    path("payments/<int:telegram_id>/", views.payment_detail, name="payment_detail"),
    path("payment/<int:telegram_id>/", views.save_payment, name="save_payment"),
    path('user-referral/<int:telegram_id>/', views.UserReferralView.as_view(), name='user-referral'),
    path("add-referral/", views.add_referral, name='user-referrals'),
    path("messages/<int:telegram_id>/", views.save_message),

    path(
        "change-login-password/",
        views.change_login_password,
        name="change_login_password",
    ),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("export-users/", views.export_users_to_excel, name="export_users_to_excel"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path("uzum-ser/", admin.site.urls),
    path("api/", include("api.urls")),
    path("", include("functions.urls")),
    # Media and static files
    re_path(r"static/(?P<path>.*)", serve, {"document_root": settings.STATIC_ROOT}),
    re_path(r"media/(?P<path>.*)", serve, {"document_root": settings.MEDIA_ROOT}),
]

api/models.py
from django.db import models


class TelegramUser(models.Model):
    telegram_id = models.CharField(max_length=50, unique=True)
    first_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    username = models.CharField(max_length=50, blank=True)
    date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.first_name


class Payment(models.Model):
    user = models.ForeignKey(TelegramUser, on_delete=models.CASCADE)
    chek = models.ImageField(upload_to="check/")
    is_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.first_name} Payment"


class Message(models.Model):
    user = models.ForeignKey(TelegramUser, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="message/", blank=True)
    video = models.FileField(upload_to="message/", blank=True)
    date = models.DateTimeField(auto_now_add=True)
    message_id = models.BigIntegerField(blank=True, null=True)
    url = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.text[:10] + "..."

class Referral(models.Model):
    user = models.OneToOneField(TelegramUser, on_delete=models.CASCADE, related_name="referral")
    invited_users = models.ManyToManyField(TelegramUser, related_name="invited_by", blank=True)
    referral_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.username or self.user.telegram_id} - {self.referral_count} referrals"

class Channel(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=300)

    def __str__(self):
        return self.name

templates/message/chat.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Dashboard</title>
  <link href="{% static 'img/favicon.png'%}" rel="icon">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"> <!-- Added Bootstrap Icons -->
</head>

<body>
    <main id="main" class="main">
    <section class="section">
        <div class="row">
          <div class="col-lg-6">
            <div class="message-container">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
        
            </div>
            <div class="card">
                    <div class="card-body">
                      <h1 class="card-title">{{ telegram_user.first_name }} ga xabar yuborish</h1>
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea id="message" class="form-control" name="text"></textarea><br>
                        </div>
                        <div class="form-group">
                            <label for="url">Button uchun URL:</label>
                            <input name="url" class="form-control" id="url" >                            
                        </div>
                        <div class="d-flex" style="gap: 30px;">
                            <div class="form-group" style="margin-top: 20px;">
                                <input type="file" id="image" accept="image/*" name="image" style="display: none;" onchange="updateFileName()">
                                <label for="image" style="cursor: pointer;">
                                    <h1><i class="bi bi-image" style="max-width: 150px;"></i></h1>
                                </label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Yuborish</button>
                    </form>
                    </div>
                  </div>
                  
            </div>
          </div>
        </div>
    </section>
    </main>

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/apexcharts/apexcharts.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'vendor/chart.js/chart.umd.js'%}"></script>
<script src="{% static 'vendor/echarts/echarts.min.js'%}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js'%}"></script>

</body>
<style>
    
</style>
</html>
{% endblock %}

templates/message/chats.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Dashboard</title>
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <main id="main" class="main">
        <section class="section">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Kiruvchi xabarlar</h5>
                            {% if user_messages %}
                                {% for user, messages in user_messages.items %}
                                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                                        <a href="{% url 'user_messages' user.telegram_id %}">
                                            {{ user.first_name }} {{ user.last_name }}
                                        </a>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <p>Hozircha xabarlar mavjud emas.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'vendor/echarts/echarts.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>
{% endblock %}

templates/message/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% extends 'base/base.html' %}
    {% load static %}
    {% block content %}
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Forms / Elements - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png'%}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png'%}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/simple-datatables/style.css'%}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css'%}" rel="stylesheet">

    <!-- SheetJS Library for Export to Excel -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
</head>

<body>

    <main id="main" class="main">
        <div class="message-container">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
    
        </div>
        <div class="pagetitle">
          <h1>Barcha foydalanuvchilar jadvali</h1>
        </div><!-- End Page Title -->
    
        <section class="section">
          <div class="row">
            <div class="col-lg-12">
    
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Barcha Foydalanuvchilar</h5>
                  <div class="mb-3">
                    <button class="btn btn-light filter-btn" style="border: 1px;" onclick="filterTable('all')">Hammasi</button>
                    <button class="btn btn-light filter-btn" style="border: 1px;" onclick="filterTable('paid')">To'lov qilganlar</button>
                    <button class="btn btn-light filter-btn" style="border: 1px;"  onclick="filterTable('unpaid')">To'lov qilmaganlar</button>
                    <a href="{% url 'export_users_to_excel' %}" class="btn btn-primary">Export to Excel</a>

                  </div>
                  <table id="dataTable" class="table datatable" style="display: block;width: 100%;overflow-x: auto; -webkit-overflow-scrolling: touch;">
                    <thead>
                      <tr>
                          <th>Telegram ID</th>
                          <th>Ismi</th>
                          <th>Telefon</th>
                          <th>Username</th>
                          <th>Holat</th>
                          <th>Amal</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for item in payments %}
                      <tr class="{% if item.has_payment %}paid{% else %}unpaid{% endif %}">
                          <td><a href="">{{item.user.telegram_id}}</a></td>
                          <td>{{ item.user.first_name }}</td>
                          <td>{{ item.user.phone }}</td>
                          <td>{{ item.user.username }}</td>
                          {% if item.has_payment %}
                             <td style="color: #6de60a;">To'lov qilingan</td>
                          {% else %}
                              <td style="color: #9e0505;">To'lov qilinmagan</td>
                          {% endif %}
                          <td>
                              <a href="{% url 'send_message' item.user.telegram_id %}" class="btn btn-primary">Xabar Yuborish</a>
                          </td>
                      </tr>
                      {% endfor %}
                  </tbody>
                  </table>
                  <!-- End Table with stripped rows -->
    
                </div>
              </div>
    
            </div>
          </div>
        </section>
    
      </main><!-- End #main -->
    
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="{% static 'vendor/simple-datatables/simple-datatables.js'%}"></script>
    <script src="{% static 'vendor/tinymce/tinymce.min.js'%}"></script>

    <!-- Template Main JS File -->
    <script>
      function filterTable(status) {
          var rows = document.querySelectorAll("#dataTable tbody tr");
          rows.forEach(function(row) {
              row.style.display = "table-row"; // Show all rows
              if (status === 'paid' && !row.classList.contains('paid')) {
                  row.style.display = "none"; // Hide unpaid rows
              } else if (status === 'unpaid' && !row.classList.contains('unpaid')) {
                  row.style.display = "none"; // Hide paid rows
              } else if (status === 'all') {
                  row.style.display = "table-row"; // Show all rows for 'Hammasi'
              }
          });

          // Update button styles
          var buttons = document.querySelectorAll('.filter-btn');
          buttons.forEach(function(button) {
              button.classList.remove('btn-primary'); // Reset to light color
              button.classList.add('btn-light');
          });
          event.target.classList.remove('btn-light'); // Set clicked button to primary color
          event.target.classList.add('btn-primary');
      }
  </script>

</body>
</html>
{% endblock content %}

templates/message/send.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Dashboard</title>
  <link href="{% static 'img/favicon.png'%}" rel="icon">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <main id="main" class="main">
    <section class="section">
        <div class="row">
          <div class="col-lg-6">
            <div class="message-container">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
        
            </div>
            <div class="card">
                    <div class="card-body">
                      <h1 class="card-title">{{title}}</h1>
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea id="message" class="form-control" name="message"></textarea><br>
                        </div>
                        <div class="form-group">
                            <label for="url">Button uchun url:</label>
                            <input name="url" class="form-control" id="url" >                            
                        </div>
                        <div class="d-flex" style="gap: 30px;">
                            <div class="form-group" style="margin-top: 20px;">
                                <input type="file" id="image" accept="image/*" name="image" style="display: none;" onchange="updateFileName()">
                                <label for="image" style="cursor: pointer;">
                                    <h1><i class="bi bi-image" style="max-width: 150px;"></i></h1>
                                </label>
                            </div>
    
                            <div class="form-group" style="margin-top: 20px;">
                                <input type="file" id="video" name="video" accept="video/*" style="display: none;" onchange="updateFileName()">
                                <label for="video" style="cursor: pointer;">
                                    <h1><i class="bi bi-caret-right-square-fill" style="max-width: 150px;"></i></h1>
                                </label>
                            </div>
                            <div class="form-group" style="margin-top: 20px;">
                                <input type="file" id="video_note" name="video_note" accept="video/*" style="display: none;" onchange="updateFileName()">
                                <label for="video_note" style="cursor: pointer;">
                                    <h1><i class="bi bi-play-circle-fill" style="max-width: 150px;"></i></h1>
                                </label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Yuborish</button>
                    </form>
                    </div>
                  </div>
                  
            </div>
          </div>
        </div>
    </section>
    </main>

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/apexcharts/apexcharts.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'vendor/chart.js/chart.umd.js'%}"></script>
<script src="{% static 'vendor/echarts/echarts.min.js'%}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js'%}"></script>

</body>
<style>
    
</style>
</html>
{% endblock %}

templates/message/user_messages.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Dashboard</title>
  <link href="{% static 'img/favicon.png'%}" rel="icon">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <main id="main" class="main">
    <section class="section">
        <div class="row">
          <div class="col-lg-6">
  
            <div class="card">
                    <div class="card-body">
                      <h1 class="card-title">{{ user.first_name }} dan kelgan xabarlar</h1>
                      <ul class="messag">
                          {% for message in messages %}
                          <h5 >{{ message.text }} - {{ message.date }}</p>
                          {% endfor %}
                      </ul>
                  
                      <h2 class="card-title">Yangi xabar yuborish</h2>
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_text">Xabar matni:</label>
                            <textarea id="id_text" name="text" class="form-control" rows="4"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="id_url">Button uchun url:</label>
                            <input name="url" class="form-control" id="id_url" >                            
                        </div>
                        <div class="d-flex" style="gap: 30px;">
                            <div class="form-group" style="margin-top: 20px;">
                                <input type="file" id="id_image" name="image" style="display: none;" onchange="updateFileName()">
                                <label for="id_image" style="cursor: pointer;">
                                    <h1><i class="bi bi-image" style="max-width: 150px;"></i></h1>
                                </label>
                            </div>
    
                            <div class="form-group" style="margin-top: 20px;">
                                <input type="file" id="id_video" name="video" style="display: none;" onchange="updateFileName()">
                                <label for="id_video" style="cursor: pointer;">
                                    <h1><i class="bi-grid" style="max-width: 150px;"></i></h1>
                                </label>
                            </div>
                        </div>
                    
                        <button type="submit" class="btn btn-primary">Yuborish</button>
                    </form>
                    </div>
                  </div>
                  
            </div>
          </div>
        </div>
    </section>
    </main>

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/apexcharts/apexcharts.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'vendor/chart.js/chart.umd.js'%}"></script>
<script src="{% static 'vendor/echarts/echarts.min.js'%}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js'%}"></script>

</body>
<style>
    
</style>
</html>
{% endblock %}